// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM2ycbmsh7vPTtNL7vnEnNl84ztPa5g2I',
    appId: '1:516174243814:web:0faae1c0c7d45dfee5d827',
    messagingSenderId: '516174243814',
    projectId: 'mindmap-3a67c',
    authDomain: 'mindmap-3a67c.firebaseapp.com',
    databaseURL: 'https://mindmap-3a67c-default-rtdb.firebaseio.com',
    storageBucket: 'mindmap-3a67c.appspot.com',
    measurementId: 'G-NRZ1KK7VJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXWWSUu51m0Num26flk1Fw_kbkFMDZGvQ',
    appId: '1:516174243814:android:859ed165627d73bce5d827',
    messagingSenderId: '516174243814',
    projectId: 'mindmap-3a67c',
    databaseURL: 'https://mindmap-3a67c-default-rtdb.firebaseio.com',
    storageBucket: 'mindmap-3a67c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDokyV0A3-CT9W55Bp2z5fOpJNh1Js9aFU',
    appId: '1:516174243814:ios:ae26705b99f669e3e5d827',
    messagingSenderId: '516174243814',
    projectId: 'mindmap-3a67c',
    databaseURL: 'https://mindmap-3a67c-default-rtdb.firebaseio.com',
    storageBucket: 'mindmap-3a67c.appspot.com',
    iosBundleId: 'com.example.mindmap2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDokyV0A3-CT9W55Bp2z5fOpJNh1Js9aFU',
    appId: '1:516174243814:ios:ae26705b99f669e3e5d827',
    messagingSenderId: '516174243814',
    projectId: 'mindmap-3a67c',
    databaseURL: 'https://mindmap-3a67c-default-rtdb.firebaseio.com',
    storageBucket: 'mindmap-3a67c.appspot.com',
    iosBundleId: 'com.example.mindmap2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM2ycbmsh7vPTtNL7vnEnNl84ztPa5g2I',
    appId: '1:516174243814:web:f6c69a26f6a25bbee5d827',
    messagingSenderId: '516174243814',
    projectId: 'mindmap-3a67c',
    authDomain: 'mindmap-3a67c.firebaseapp.com',
    databaseURL: 'https://mindmap-3a67c-default-rtdb.firebaseio.com',
    storageBucket: 'mindmap-3a67c.appspot.com',
    measurementId: 'G-CLB4VKGH3B',
  );
}
